#!/bin/bash

# required
set -e

# fix permissions
chown -R odroid:odroid /opt/navcoin-angular

# reload systemctl daemon
systemctl daemon-reload

# enable navcoin-angular on boot
systemctl enable navcoin-angular

echo 
echo "Start with: systemctl start navcoin-angular"
echo
