#!/bin/bash

# fix permissions
chown -R odroid:odroid /opt/navcoin-angular

# reload systemctl daemon
systemctl daemon-reload

# enable navcoin-angular on boot
systemctl enable navcoin-angular
systemctl start navcoin-angular

echo 
echo "navcoin-angular started"
echo
echo "Manage with: systemctl start|stop|restart navcoin-angular"
echo
