#!/bin/bash

# required
set -e

# reload systemctl daemon
systemctl daemon-reload

# enable navcoin-angular on boot
systemctl enable navcoin-angular

echo 
echo "Start with: systemctl start navcoin-angular"
echo
